# Generated by Django 4.0.5 on 2022-07-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_release_data_movie_release_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor_movie',
            table='actor_movie',
        ),
    ]
