# Generated by Django 4.0.5 on 2022-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_movie_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='add_to_actor',
            field=models.ManyToManyField(to='movies.actor'),
        ),
    ]
